/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Model.glb 
*/

import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useRef } from "react";
import * as THREE from "three";
import { useSelector } from "react-redux";
import { useLoader } from "@react-three/fiber";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Model.glb");
  const [albedo, normal, roughness, metalness, ao] = useLoader(
    THREE.TextureLoader,
    [
      "/textures/black-leather_albedo.png",
      "/textures/black-leather_normal-ogl.png",
      "/textures/black-leather_roughness.png",
      "/textures/black-leather_metallic.png",
      "/textures/black-leather_ao.png",
    ]
  );
  useEffect(() => {
    const materialNames = [
      "Wing Toe Material",
      "Wing Toe Body Material",
      "Wing Toe Back Material",
      "Wing Toe Side Parts Material",
      "Wing Toe Front Material",
      "Wing Toe Inner Body Material",
      "Thread Material",
      "Whole Cut Body Material",
      "Wing Toe Inner Body Material",
    ];

    materialNames.forEach((name) => {
      if (materials[name]) {
        [albedo, normal, roughness, metalness, ao].forEach((texture) => {
          if (texture) {
            texture.wrapS = texture.wrapT = THREE.RepeatWrapping;
            texture.anisotropy = 18;
            texture.repeat.set(5, 5); // More balanced scale for natural leather
          }
        });

        materials[name].map = albedo;
        materials[name].normalMap = normal;
        materials[name].roughnessMap = roughness;
        materials[name].metalnessMap = metalness;
        materials[name].aoMap = ao;

        // 🎯 Soft, Premium Leather Adjustments
        materials[name].roughness = 0.9; // Lower roughness for soft sheen
        materials[name].metalness = 0.01; // Almost non-metallic
        materials[name].aoMapIntensity = 6; // Stronger ambient occlusion for depth
        // materials[name].displacementScale = 0.001; // Subtle depth for softness
        // materials[name].displacementBias = -0.0005;

        // ✅ Enhance Leather Grain & Surface Detail
        materials[name].normalScale = new THREE.Vector2(0.5, 0.5); // Soft grain effect

        // ✅ Add Clearcoat for Luxury Finish
        materials[name].clearcoat = 0; // Adds a thin glossy layer
        materials[name].clearcoatRoughness = 2; // Slightly softens reflections

        materials[name].needsUpdate = true;
      }
    });
  }, [materials, albedo, normal, roughness, metalness, ao]);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Sole_Pad.geometry}
        material={materials["Sole Pad Material"]}
        position={[0, -0.004, 0]}
        scale={[0.146, 0.149, 0.146]}
      />
      <mesh
        geometry={nodes.Wing_Toe_Body.geometry}
        material={materials["Wing Toe Inner Body Material"]}
        position={[0, -0.009, 0]}
        scale={0.149}
      />
      <mesh
        geometry={nodes.Piece_Under_Meddalion.geometry}
        material={materials["Wing Toe Material"]}
        position={[0, -0.01, 0]}
        scale={0.149}
      />
      <mesh
        geometry={nodes.Wing_Toe_Body003.geometry}
        material={materials["Wing Toe Material"]}
        position={[0, -0.009, 0]}
        scale={0.149}
      />
      <mesh
        geometry={nodes.Wing_Toe_Body004.geometry}
        material={materials["Wing Toe Body Material"]}
        position={[0, -0.009, 0]}
        scale={0.149}
      />
      <mesh
        geometry={nodes.Wing_Toe_Body005.geometry}
        material={materials["Wing Toe Front Material"]}
        position={[0, -0.009, 0]}
        scale={0.149}
      />
      <mesh
        geometry={nodes.Wing_Toe_Body006.geometry}
        material={materials["Wing Toe Back Material"]}
        position={[0, -0.009, -0.001]}
        scale={0.149}
      />
      <mesh
        geometry={nodes.Wing_Toe_Body007.geometry}
        material={materials["Wing Toe Side Parts Material"]}
        position={[0, -0.009, 0]}
        scale={0.149}
      />
      <mesh
        geometry={nodes.Wing_Toe_Eyelets.geometry}
        material={materials["EyeLets Material"]}
        position={[0, -0.009, 0]}
        scale={0.149}
      />
      <mesh
        geometry={nodes.Sole_Thread_Path_For_Wing_Toe.geometry}
        material={materials["Thread Material"]}
        position={[0.008, 0.007, -0.016]}
        rotation={[0, 0.142, 0]}
        scale={1.02}
      />
      <mesh
        geometry={nodes.Wing_Toe_Thread_Path_6_Stich_Back_Side_Left.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Wing_Toe_Thread_Path_6_Stich_Back_Side_Left001.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Wing_Toe_Thread_Path_6_Stich_Back_Side_Right.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={
          nodes.Wing_Toe_Thread_Path_6_Stich_Back_Side_Right001.geometry
        }
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Wing_Toe_Thread_Path_10_Stich_Middle.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Wing_Toe_Thread_Path_11_Stich_Middle.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Wing_Toe_Thread_Path_12_Middle_Stich.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Wing_Toe_Thread_Path_13_Middle_Stich.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Wing_Toe_Thread_Top.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Wing_Toe_Thread_Top002.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Wing_Toe_Thread_Top003.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Wing_Toe_Thread_Top004.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Wing_Toe_Thread_Top_Sides_Outer.geometry}
        material={materials["Thread Material"]}
      />
      <group position={[0.005, 0.088, -0.001]}>
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials["Inner Piece Top Material"]}
        />
        <mesh
          geometry={nodes.Plane001_1.geometry}
          material={materials["Inner Piece Inner Material"]}
        />
      </group>
      <mesh
        geometry={nodes.Inner_Piece_of_Shoe_thread_Path_Stich.geometry}
        material={materials["Sole Pad"]}
      />
      <mesh
        geometry={nodes.Inner_Piece_of_Shoe_thread_Path_Stich_Wing_Toe.geometry}
        material={materials["Sole Pad"]}
      />
      <group position={[0.012, 0.008, 0.03]}>
        <mesh geometry={nodes.Cube007.geometry} material={materials.Sole} />
        <mesh geometry={nodes.Cube007_1.geometry} material={materials.Points} />
        <mesh
          geometry={nodes.Cube007_2.geometry}
          material={materials["Brown Bottom"]}
        />
        <mesh geometry={nodes.Cube007_3.geometry} material={materials.Heel} />
      </group>
      <group position={[0.012, 0.008, 0.03]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials.Sole} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.Points} />
        <mesh
          geometry={nodes.Cube003_2.geometry}
          material={materials["Brown Bottom"]}
        />
        <mesh geometry={nodes.Cube003_3.geometry} material={materials.Heel} />
        <mesh
          geometry={nodes.Cube003_4.geometry}
          material={materials["Leather Mid Sole"]}
        />
      </group>
      <group position={[0.007, 0.002, 0.029]} rotation={[0.008, 0, 0.013]}>
        <mesh geometry={nodes.Cube014.geometry} material={materials.Sole} />
        <mesh
          geometry={nodes.Cube014_1.geometry}
          material={materials["Brown Bottom"]}
        />
      </group>
      <mesh
        geometry={nodes.Lace_1.geometry}
        material={materials["Laces.001"]}
        position={[0.005, 0.087, 0.038]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Lace_2.geometry}
        material={materials["Laces.001"]}
        position={[0.003, 0.093, 0.028]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Lace_3.geometry}
        material={materials["Laces.001"]}
        position={[0, 0.101, 0.02]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Lace_4.geometry}
        material={materials["Laces.001"]}
        position={[-0.002, 0.107, 0.011]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Lace_5.geometry}
        material={materials["Laces.001"]}
        position={[-0.005, 0.112, 0.002]}
        scale={0.032}
      />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Sole} />
      <mesh
        geometry={nodes.Cube004_1.geometry}
        material={materials["Wood Sole"]}
      />
      <mesh
        geometry={nodes.Cube004_2.geometry}
        material={materials["Sole Bottom"]}
      />
    </group>
  );
}

useGLTF.preload("/Model.glb");
