/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Command: npx gltfjsx@6.5.3 Oxfords.glb 
  */

import React, { useState } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export function Model(props) {
  const { nodes } = useGLTF("./Oxfords.glb");
  const [hoveredPart, setHoveredPart] = useState(null);

  // Load only the normal map for subtle surface detail
  const normalMap = useTexture("/textures/black-leather_normal-ogl.png");

  // Function to create material with hover effect
  const createMaterial = (baseMaterial, partName) => {
    const isHovered = hoveredPart === partName;
    return new THREE.MeshStandardMaterial({
      ...baseMaterial,
      color: isHovered
        ? new THREE.Color().lerpColors(
            new THREE.Color(baseMaterial.color),
            new THREE.Color(0xffffff),
            0.08 // Very subtle white overlay (8% opacity)
          )
        : new THREE.Color(baseMaterial.color),
    });
  };

  // Base materials
  const baseLeatherMaterial = {
    color: 0x1a1a1a,
    roughness: 0.5,
    metalness: 0.7,
    normalMap: normalMap,
    normalScale: new THREE.Vector2(0.08, 0.08),
  };

  const baseSoleMaterial = {
    color: 0x0f0f0f,
    roughness: 0.8,
    metalness: 0.0,
  };

  const baseLacesMaterial = {
    color: 0x1a1a1a,
    roughness: 0.8,
  };

  const baseEyeletsMaterial = {
    color: 0x888888,
    metalness: 0.8,
    roughness: 0.2,
  };
  return (
    <group {...props} dispose={null}>
      <group position={[-0.128, -0.07, -0.025]} scale={0.5}>
        <mesh
          geometry={nodes.Cube022.geometry}
          material={createMaterial(baseSoleMaterial, "sole1")}
          onPointerEnter={() => {
            setHoveredPart("sole1");
            document.body.style.cursor = "pointer";
          }}
          onPointerLeave={() => {
            setHoveredPart(null);
            document.body.style.cursor = "default";
          }}
        />
        <mesh
          geometry={nodes.Cube022_1.geometry}
          material={createMaterial(baseLeatherMaterial, "upper1")}
          onPointerEnter={() => {
            setHoveredPart("upper1");
            document.body.style.cursor = "pointer";
          }}
          onPointerLeave={() => {
            setHoveredPart(null);
            document.body.style.cursor = "default";
          }}
        />
      </group>
      <mesh
        geometry={nodes.Cube004.geometry}
        material={createMaterial(baseLeatherMaterial, "leather1")}
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
        onPointerEnter={() => {
          setHoveredPart("leather1");
          document.body.style.cursor = "pointer";
        }}
        onPointerLeave={() => {
          setHoveredPart(null);
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={createMaterial(baseLeatherMaterial, "leather2")}
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
        onPointerEnter={() => {
          setHoveredPart("leather2");
          document.body.style.cursor = "pointer";
        }}
        onPointerLeave={() => {
          setHoveredPart(null);
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={createMaterial(baseLeatherMaterial, "leather3")}
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
        onPointerEnter={() => {
          setHoveredPart("leather3");
          document.body.style.cursor = "pointer";
        }}
        onPointerLeave={() => {
          setHoveredPart(null);
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={createMaterial(baseLeatherMaterial, "leather4")}
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
        onPointerEnter={() => {
          setHoveredPart("leather4");
          document.body.style.cursor = "pointer";
        }}
        onPointerLeave={() => {
          setHoveredPart(null);
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={createMaterial(baseLeatherMaterial, "leather5")}
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
        onPointerEnter={() => {
          setHoveredPart("leather5");
          document.body.style.cursor = "pointer";
        }}
        onPointerLeave={() => {
          setHoveredPart(null);
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={createMaterial(baseLeatherMaterial, "leather6")}
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
        onPointerEnter={() => {
          setHoveredPart("leather6");
          document.body.style.cursor = "pointer";
        }}
        onPointerLeave={() => {
          setHoveredPart(null);
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={createMaterial(baseLeatherMaterial, "leather7")}
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
        onPointerEnter={() => {
          setHoveredPart("leather7");
          document.body.style.cursor = "pointer";
        }}
        onPointerLeave={() => {
          setHoveredPart(null);
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={createMaterial(baseLeatherMaterial, "leather8")}
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
        onPointerEnter={() => {
          setHoveredPart("leather8");
          document.body.style.cursor = "pointer";
        }}
        onPointerLeave={() => {
          setHoveredPart(null);
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={createMaterial(baseLeatherMaterial, "leather9")}
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
        onPointerEnter={() => {
          setHoveredPart("leather9");
          document.body.style.cursor = "pointer";
        }}
        onPointerLeave={() => {
          setHoveredPart(null);
          document.body.style.cursor = "default";
        }}
      />
      <group
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
      >
        <mesh
          geometry={nodes.Cube089.geometry}
          material={createMaterial(baseLacesMaterial, "laces")}
          onPointerEnter={() => {
            setHoveredPart("laces");
            document.body.style.cursor = "pointer";
          }}
          onPointerLeave={() => {
            setHoveredPart(null);
            document.body.style.cursor = "default";
          }}
        />
        <mesh
          geometry={nodes.Cube089_1.geometry}
          material={createMaterial(baseEyeletsMaterial, "eyelets1")}
          onPointerEnter={() => {
            setHoveredPart("eyelets1");
            document.body.style.cursor = "pointer";
          }}
          onPointerLeave={() => {
            setHoveredPart(null);
            document.body.style.cursor = "default";
          }}
        />
      </group>
      <mesh
        geometry={nodes.Cube011.geometry}
        material={createMaterial(baseEyeletsMaterial, "eyelets2")}
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
        onPointerEnter={() => {
          setHoveredPart("eyelets2");
          document.body.style.cursor = "pointer";
        }}
        onPointerLeave={() => {
          setHoveredPart(null);
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={createMaterial(baseEyeletsMaterial, "eyelets3")}
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
        onPointerEnter={() => {
          setHoveredPart("eyelets3");
          document.body.style.cursor = "pointer";
        }}
        onPointerLeave={() => {
          setHoveredPart(null);
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={createMaterial(baseEyeletsMaterial, "eyelets4")}
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
        onPointerEnter={() => {
          setHoveredPart("eyelets4");
          document.body.style.cursor = "pointer";
        }}
        onPointerLeave={() => {
          setHoveredPart(null);
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={createMaterial(baseLeatherMaterial, "leather10")}
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
        onPointerEnter={() => {
          setHoveredPart("leather10");
          document.body.style.cursor = "pointer";
        }}
        onPointerLeave={() => {
          setHoveredPart(null);
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={createMaterial(baseLeatherMaterial, "leather11")}
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
        onPointerEnter={() => {
          setHoveredPart("leather11");
          document.body.style.cursor = "pointer";
        }}
        onPointerLeave={() => {
          setHoveredPart(null);
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={createMaterial(baseLeatherMaterial, "leather12")}
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
        onPointerEnter={() => {
          setHoveredPart("leather12");
          document.body.style.cursor = "pointer";
        }}
        onPointerLeave={() => {
          setHoveredPart(null);
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={createMaterial(baseSoleMaterial, "sole2")}
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
        onPointerEnter={() => {
          setHoveredPart("sole2");
          document.body.style.cursor = "pointer";
        }}
        onPointerLeave={() => {
          setHoveredPart(null);
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        geometry={nodes.Cube023.geometry}
        material={createMaterial(baseLeatherMaterial, "leather13")}
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
        onPointerEnter={() => {
          setHoveredPart("leather13");
          document.body.style.cursor = "pointer";
        }}
        onPointerLeave={() => {
          setHoveredPart(null);
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={createMaterial(baseLeatherMaterial, "leather14")}
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
        onPointerEnter={() => {
          setHoveredPart("leather14");
          document.body.style.cursor = "pointer";
        }}
        onPointerLeave={() => {
          setHoveredPart(null);
          document.body.style.cursor = "default";
        }}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={createMaterial(baseLeatherMaterial, "leather15")}
        position={[-0.138, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.1}
        onPointerEnter={() => {
          setHoveredPart("leather15");
          document.body.style.cursor = "pointer";
        }}
        onPointerLeave={() => {
          setHoveredPart(null);
          document.body.style.cursor = "default";
        }}
      />
    </group>
  );
}

useGLTF.preload("./Oxfords.glb");
