/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\oxford-models\CapToe-draco.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function CapToeModel(props) {
  const { nodes, materials } = useGLTF("/oxford-models/CapToe-draco.glb");
  return (
    <group {...props} dispose={null} scale={[10, 10, 10]}>
      <mesh
        geometry={nodes.Sole_Pad.geometry}
        material={materials["Inner Piece of Inner Piece"]}
        position={[0, -0.004, 0]}
        scale={[0.146, 0.149, 0.146]}
      />
      <group position={[0, -0.009, 0]} scale={0.149}>
        <mesh
          geometry={nodes.Cube003.geometry}
          material={materials["Cap Toe Side Parts Material"]}
          material-color="red"
        />
        <mesh
          geometry={nodes.Cube003_1.geometry}
          material={materials["Cap Toe Inner Material"]}
          material-color="brown"
        />
      </group>
      <group position={[0, -0.009, 0]} scale={0.149}>
        <mesh
          geometry={nodes.Cube001.geometry}
          material={materials["Cap Toe Material"]}
          material-color="green"
        />
        <mesh
          geometry={nodes.Cube001_1.geometry}
          material={materials["Cap Toe Body Material"]}
        />
        <mesh
          geometry={nodes.Cube001_2.geometry}
          material={materials["Cap Toe Inner Material"]}
        />
      </group>
      <mesh
        geometry={nodes.Cap_Toe_Eyelets.geometry}
        material={materials["EyeLets Material"]}
        position={[0, -0.009, 0]}
        scale={0.149}
      />
      <mesh
        geometry={nodes.Cap_Toe.geometry}
        material={materials["Cap Toe Material"]}
        position={[0, -0.009, 0]}
        scale={0.149}
      />
      <mesh
        geometry={nodes.Cap_Toe_Body002.geometry}
        material={materials["Cap Toe Body Material"]}
        position={[0, -0.009, 0]}
        scale={0.149}
        material-color="blue"
      />
      <mesh
        geometry={nodes.Cap_Toe_Body003.geometry}
        material={materials["Cap Toe Front Material"]}
        position={[0, -0.009, 0]}
        scale={0.149}
        material-color="yellow"
      />
      <mesh
        geometry={nodes.Cap_Toe_Body004.geometry}
        material={materials["Cap Toe Back Part Material"]}
        position={[0, -0.009, 0]}
        scale={0.149}
        material-color="black"
      />
      <mesh
        geometry={nodes.Cap_Toe__Thread_Path_9_Stich_Back.geometry}
        material={materials["Thread Material"]}
        position={[0, 0, -0.003]}
      />
      <mesh
        geometry={nodes.Cap_Toe__Thread_Path_10_Stich_Middle.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Cap_Toe__Thread_Path_13_Middle_Stich.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Cap_Toe__Thread_Top_Sides_Outer.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Cap_Toe_Inner_Thread_Top_Sides001.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Cap_Toe_Thread_Path_4_Stich_Back_Left.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Cap_Toe_Thread_Path_6_Stich_Back_Side_Right.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Cap_Toe_Thread_Path_8_Stich_Back.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Cap_Toe_Thread_Path_11_Stich_Middle001.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Cap_Toe_Thread_Path_11_Stich_Middle002.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Cap_Toe_Thread_Path_11_Stich_Middle003.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Cap_Toe_Thread_Path_12_Middle_Stich.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Cap_Toe_Thread_Top.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Cap_Toe_Thread_Top001.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Sole_Thread_Path_For_Cap_Toe_.geometry}
        material={materials["Thread Material"]}
        position={[0.008, 0.007, -0.016]}
        rotation={[0, 0.142, 0]}
        scale={1.02}
      />
      <group position={[0.012, 0.008, 0.03]}>
        <mesh
          geometry={nodes.Cube007.geometry}
          material={materials["Sole.001"]}
        />
        <mesh geometry={nodes.Cube007_1.geometry} material={materials.Points} />
        <mesh
          geometry={nodes.Cube007_2.geometry}
          material={materials["Brown Bottom"]}
        />
        <mesh geometry={nodes.Cube007_3.geometry} material={materials.Heel} />
      </group>
      <group position={[0.012, 0.008, 0.03]}>
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials["Sole.001"]}
        />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.Points} />
        <mesh
          geometry={nodes.Cube002_2.geometry}
          material={materials["Brown Bottom"]}
        />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials.Heel} />
        <mesh
          geometry={nodes.Cube002_4.geometry}
          material={materials["Leather Mid Sole"]}
        />
      </group>
      <group position={[0.007, 0.002, 0.029]} rotation={[0.008, 0, 0.013]}>
        <mesh
          geometry={nodes.Cube014.geometry}
          material={materials["Sole.001"]}
        />
        <mesh
          geometry={nodes.Cube014_1.geometry}
          material={materials["Brown Bottom"]}
        />
      </group>
      <group position={[0.005, 0.088, -0.001]}>
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials["Outer Part of Inner Piece Material"]}
        />
        <mesh
          geometry={nodes.Plane001_1.geometry}
          material={materials["Inner Part of Inner Piece Material"]}
        />
      </group>
      <mesh
        geometry={nodes.Inner_Piece_of_Shoe_thread_Path_Stich_Cap_Toe_.geometry}
        material={materials["Thread Material"]}
      />
      <mesh
        geometry={nodes.Lace_1.geometry}
        material={materials["Laces.002"]}
        position={[0.005, 0.087, 0.038]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Lace_2.geometry}
        material={materials["Laces.002"]}
        position={[0.003, 0.093, 0.028]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Lace_3.geometry}
        material={materials["Laces.002"]}
        position={[0, 0.101, 0.02]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Lace_4.geometry}
        material={materials["Laces.002"]}
        position={[-0.002, 0.107, 0.011]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Lace_5.geometry}
        material={materials["Laces.002"]}
        position={[-0.005, 0.112, 0.002]}
        scale={0.032}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials["Sole.001"]}
      />
      <mesh
        geometry={nodes.Cube004_1.geometry}
        material={materials["Wood Sole"]}
      />
      <mesh
        geometry={nodes.Cube004_2.geometry}
        material={materials["Sole Bottom"]}
      />
    </group>
  );
}

useGLTF.preload("/CapToe-draco.glb");
